import { Article, Category } from "../types";

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: 'Health', icon: 'favorite' },
  { id: 2, name: 'Wellness', icon: 'spa' },
  { id: 3, name: 'Lifestyle', icon: 'home' },
  { id: 4, name: 'Career', icon: 'work' },
  { id: 5, name: 'Relationships', icon: 'people' },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: 1,
    title: 'Understanding Hormonal Health in Your 30s',
    excerpt: 'Essential insights into maintaining hormonal balance and wellness during your thirties. Learn about the key changes and how to adapt your lifestyle.',
    author: 'Dr. Sarah Johnson',
    category: 'Health',
    publishedAt: '2024-01-15',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    readTime: 5,
    likes: 234,
    isBookmarked: false,
  },
  {
    id: 2,
    title: 'Building Healthy Morning Routines',
    excerpt: 'Discover how to create a morning routine that sets you up for success. Simple, sustainable habits that make a real difference.',
    author: 'Emma Wilson',
    category: 'Wellness',
    publishedAt: '2024-01-14',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    readTime: 4,
    likes: 189,
    isBookmarked: true,
  },
  {
    id: 3,
    title: 'Navigating Career Transitions with Confidence',
    excerpt: 'Expert advice on making career changes at any stage. Learn how to identify opportunities and overcome fear.',
    author: 'Lisa Chen',
    category: 'Career',
    publishedAt: '2024-01-13',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800',
    readTime: 7,
    likes: 312,
    isBookmarked: false,
  },
  {
    id: 4,
    title: 'The Power of Mindful Communication',
    excerpt: 'Transform your relationships through better communication. Practical tips for expressing yourself authentically.',
    author: 'Maya Patel',
    category: 'Relationships',
    publishedAt: '2024-01-12',
    imageUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800',
    readTime: 6,
    likes: 267,
    isBookmarked: false,
  },
  {
    id: 5,
    title: 'Sustainable Living: Small Changes, Big Impact',
    excerpt: 'Practical ways to make your lifestyle more sustainable without overwhelming yourself. Start with these easy swaps.',
    author: 'Rachel Green',
    category: 'Lifestyle',
    publishedAt: '2024-01-11',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800',
    readTime: 5,
    likes: 421,
    isBookmarked: true,
  },
];